rpc :
  "helius":
    url: "https://staked.helius-rpc.com?api-key=<ApiKey>"
  "mainnet":
    url: "https://mainnet-beta.solana.com"
  "blockxroute":
      url: "https://uk.solana.dex.blxrbdn.com/api/v2/submit"
      auth: "<Auth>"
      rpc_type: "blockxroute"
  "jito":
    url: "https://frankfurt.mainnet.block-engine.jito.wtf"
    rpc_type: "jito"

txns_per_run: 1
txn_delay: 5
runs: 5
http_rpc: "https://staked.helius-rpc.com?api-key=<ApiKey>"
ws_rpc: "wss://staked.helius-rpc.com?api-key=<ApiKey>"
keypair_dir: "/Users/<User>/.config/solana/id.json"
compute_unit_price: 10000 #microlamports
compute_unit_limit: 2500
tip: 1000000 #lamports
verbose_log: false